// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ__yY8yLc_ZtvU3sUao08BvzIYBWSfSM',
    appId: '1:402948781960:web:5e0b947280a14bceb3ac3d',
    messagingSenderId: '402948781960',
    projectId: 'bookworm-972ae',
    authDomain: 'bookworm-972ae.firebaseapp.com',
    storageBucket: 'bookworm-972ae.appspot.com',
    measurementId: 'G-SLMM1N2W87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdAByNY_w9eobSuyACNdVOjfKfq8iaM8',
    appId: '1:402948781960:android:aa950deb4dc3ddb2b3ac3d',
    messagingSenderId: '402948781960',
    projectId: 'bookworm-972ae',
    storageBucket: 'bookworm-972ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lY9SZvCg9o3D3-IB6nZSLKWoGtZ6h9Y',
    appId: '1:402948781960:ios:eb012e235b967844b3ac3d',
    messagingSenderId: '402948781960',
    projectId: 'bookworm-972ae',
    storageBucket: 'bookworm-972ae.appspot.com',
    iosClientId: '402948781960-pv7h5m3hh2ejqide5iu5i4fgt4n5gr9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookworm',
  );
}
